services:
  backend:
    build: .
    ports:
      - "3006:3001"
    command: npm run dev_docker
    volumes:
      - "./src:/app/src" #! Not readonly.   Avoid it if you plan on using prisma which generates the client in the src folder. 
    
  test:
    build: .
    command: npm run test